//Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be :

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.

#include <iostream>

void fibs(int max)
{
	int x = 0;
	int y = 1;
	int z = 0;
	int total = 0;

		do
		{
			z = x + y;
			x = y;
			y = z;

			if (z % 2 == 0)
			{
				total = total + z;
			}
			
			if (z > max) break;

		} while (z < max);

		std::cout << "The sum of of all even Fibonacci sequence numbers less than "
			<< max << " is: " << total << std::endl;

}

int main()
{
	fibs(10);
	
	system("pause");
	return 0;
}